### ISSUE TITLE
Propose to convert to PackedScene with mesh instance, 2d mesh and 2d vgpath

### ISSUE THREAD

**Issue by fire** [poke1024/godot_vector_graphics#4]
I propose to convert to three types: 3d scene with mesh instances, 2d scene with vgpath and 2d scene with meshinstance2d.

Currently did the mostly complicated scheme which is the 3d mesh.

Any comments?

Here are some videos.

![image](https://user-images.githubusercontent.com/32321/75611050-a4533980-5acb-11ea-896b-e828224c3a9b.png)

![image](https://user-images.githubusercontent.com/32321/75611047-9b626800-5acb-11ea-8ade-7e8bca8dd942.png)

https://cdn.discordapp.com/attachments/659280732673409024/683252767787450368/2020-02-29_01-53-46.mp4

https://upload.wikimedia.org/wikipedia/commons/f/fd/Ghostscript_Tiger.svg

Will post a branch / pr for review.

I'm looking for advice and design suggestion for reducing the draw calls for the tiger.

**Comment by fire** [comment]
You can review here https://github.com/firea/godot_vector_graphics.

**Comment by fire** [comment]
I got stuck. Somewhere in this code causes the vgpath to not refresh correctly, but it works if I move the entire vgpath.

![image](https://user-images.githubusercontent.com/32321/75616152-835a0b00-5b02-11ea-950f-b0ac3de12922.png)

**Comment by fire** [comment]
I resolved an issue with colors not showing.

SRGB colours must be matches, normals and tangents must be generated.

Sidenote: I broke gradients. Not sure where to start to debug.

**Comment by jebedaia360** [comment]
Can I use this in godot 3.2?

**Comment by fire** [comment]
@jebedaia360 This branch doesn't correctly port the gradients, but it's on the 3.2 branch.

I recommend using https://github.com/godotengine/godot/pull/36922.

@poke1024 Can you take a look at my code to understand why gradients are broken? Or at least explain how they work?

**Comment by fire** [comment]
I decided to focus on vgpath and animations. https://github.com/godot-extended-libraries/lottie 

https://airbnb.design/lottie/
